### ISSUE TITLE
broken tool replacement (1.11)

### ISSUE THREAD

**Issue by TheoRetisch1** [crazyhorse961/AutomaticInventory#1]
Broken tools that are not being replaced. It doesnt matter if they are enchanted or not, none get replaced.
The problem occur only in 1.11.

[Testsystem: PaperSpigiot 1.11 (Build 960); no error]

**Comment by crazyhorse961** [comment]
Ill look into, that's strange for the fact that 1.11 didn't made any changes on that.

**Comment by TheoRetisch1** [comment]
Will you ever find time and motivation to fix the remaining bugs of the plugin or is your once annonced fork project closed for ever?

**Comment by TheoRetisch1** [comment]
This fork is dead. It is no longer continued so it is not worth keeping the tickets open anymore. It was a nice try but it never worked, because Crazy never found the time to fix anything. For everyone else who reads this: RoboMWM alias The_PC_Tech_Guy has created a 1.13.2 fork. He is quite active and the plugin works fine.
